export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function Contacts() {
  return (
    <div>
      {/* section for the car image */}

      {/* section for the contact */}
      <h1 className="font-bold py-2 text-4xl">Contact</h1>
      {/* Sponsoring */}
      {/* Student join */}
    </div>
  );
}
