import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Link from "next/link";
import Image from "next/image";
import Nav from "./components/hamburgermenu/hamburgermenu.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Illini EV Concept",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap');
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <div
      className="sticky top-0 z-50 p-1.5 flex flex-row gap-4 text-white text-xl items-center font-montserrat"
      style={{ backgroundColor: "#07407B" }}
    >
      <div className="transition duration-300 hover:scale-110">
        <Link href="/">
          <Image src="/images/evlogo.png" alt="evlogo" width="60" height="60" />
        </Link>
      </div>
      <div className="md:hidden ml-auto pr-4">
        <Nav />
      </div>
      <div className=" hidden md:flex flex ml-auto mr-10 gap-10 ">
        <div className="transition duration-300 hover:text-[#F7931E]">
          <Link href="/about">ABOUT</Link>
        </div>
        <div className="transition duration-300 hover:text-[#F7931E]">
          <Link href="/team">OUR TEAM</Link>
        </div>
        <div className="transition duration-300 hover:text-[#F7931E]">
          <Link href="/cars">OUR CARS</Link>
        </div>
        <div className="transition duration-300 hover:text-[#F7931E]">
          <Link href="/sponsors">SPONSORS</Link>
        </div>
        <div className="transition duration-300 hover:text-[#F7931E]">
          <Link href="/contacts">CONTACT US</Link>
        </div>
      </div>
    </div>
  );
}

function Footer() {
  return (
    <div className="bg-gray-100 flex items-center justify-between flex-shrink-0 text-black p-1.5 relative">
      <div className="ml-3 flex flex-row gap-2 items-center">
        <a
          href="https://www.linkedin.com/company/illini-ev-concept/"
          target="_blank"
          rel="noreferrer"
        >
          <svg
            className="fill-[#1a1a1a] transition duration-200 hover:fill-[#6d6d6d]"
            version="1.0"
            xmlns="http://www.w3.org/2000/svg"
            width="40px"
            height="40px"
            viewBox="0 0 448.000000 448.000000"
            preserveAspectRatio="xMidYMid meet"
          >
            <g
              transform="translate(0.000000,448.000000) scale(0.100000,-0.100000)"
              stroke="none"
            >
              <path
                d="M1990 4469 c-738 -83 -1405 -541 -1737 -1194 -174 -342 -253 -664
                    -253 -1032 0 -355 72 -665 230 -990 260 -534 729 -944 1299 -1133 561 -187
                    1145 -151 1676 104 466 224 814 569 1040 1031 112 228 173 423 212 675 24 158
                    24 472 0 628 -61 389 -216 757 -445 1052 -378 486 -930 793 -1547 860 -106 12
                    -368 11 -475 -1z m-474 -1034 c61 -18 127 -73 156 -129 32 -63 36 -159 8 -224
                    -48 -111 -151 -168 -289 -160 -88 5 -139 27 -194 84 -54 56 -71 108 -65 200 6
                    84 31 131 100 187 66 53 187 71 284 42z m1537 -700 c211 -44 353 -191 419
                    -430 21 -77 22 -102 26 -602 l3 -523 -255 0 -254 0 -4 468 c-4 402 -7 474 -21
                    518 -38 116 -116 176 -230 177 -111 1 -193 -51 -249 -156 -23 -41 -23 -48 -28
                    -522 l-5 -480 -252 -3 -253 -2 0 765 0 765 255 0 255 0 0 -102 0 -101 28 39
                    c74 101 197 176 322 197 57 10 179 6 243 -8z m-1383 -790 l0 -765 -255 0 -255
                    0 0 765 0 765 255 0 255 0 0 -765z"
              />
            </g>
          </svg>
        </a>
        <a
          className="align-center"
          href="https://www.instagram.com/illinievconcept/"
          target="_blank"
          rel="noreferrer"
        >
          <svg
            className="fill-[#1a1a1a] transition duration-200 hover:fill-[#6d6d6d]"
            version="1.0"
            xmlns="http://www.w3.org/2000/svg"
            width="40px"
            height="40px"
            viewBox="0 0 448.000000 448.000000"
            preserveAspectRatio="xMidYMid meet"
            transform="scale(1.4) translate(0, -4.5)"
          >
            <g stroke="none">
              <path d="m 257.129 129.761 c -40.7336 0 -45.8401 0.25899 -61.8374 0.91733 c -15.9644 0.7292 -26.846 3.22727 -36.3856 6.93669 c -9.8635 3.83171 -18.2621 8.98306 -26.6002 17.3216 c -8.33835 8.33859 -13.4417 16.6912 -17.2741 26.5541 c -3.70877 9.54051 -6.25479 20.4665 -6.98302 36.431 c -0.73154 15.9973 -0.91968 21.104 -0.91968 61.8372 c 0 40.7355 0.18808 45.8398 0.91968 61.8372 c 0.72919 15.9644 3.27425 26.8458 6.98302 36.3863 c 3.83243 9.86278 8.93577 18.2155 17.2741 26.554 c 8.33811 8.33859 16.7367 13.4853 26.6002 17.3193 c 9.53961 3.70708 20.4212 6.25455 36.3856 6.98374 c 15.9973 0.7292 21.1038 0.87029 61.8374 0.87029 c 40.7336 0 45.8398 -0.23496 61.8374 -0.87029 c 15.9642 -0.72919 26.8918 -3.27666 36.4315 -6.98374 c 9.8635 -3.83405 18.2162 -8.98071 26.5543 -17.3193 c 8.33835 -8.33854 13.4415 -16.6912 17.2739 -26.554 c 3.70876 -9.54057 6.25503 -20.4219 6.98326 -36.3863 c 0.73154 -15.9973 0.91968 -21.1016 0.91968 -61.8372 c 0 -40.7332 -0.18808 -45.8398 -0.91968 -61.8372 c -0.7292 -15.9644 -3.2745 -26.8905 -6.98326 -36.431 c -3.83243 -9.86284 -8.93553 -18.2155 -17.2739 -26.5541 c -8.33811 -8.33859 -16.6908 -13.4899 -26.5543 -17.3216 c -9.53962 -3.70942 -20.4673 -6.20749 -36.4315 -6.93669 c -15.9973 -0.72919 -21.1038 -0.91733 -61.8374 -0.91733 Z m 0 27.0128 c 40.0477 0 44.7809 0.23495 60.5968 0.87028 c 14.623 0.65865 22.6014 3.13785 27.8866 5.19137 c 7.00117 2.72149 11.9801 5.96281 17.2281 11.2106 c 5.24894 5.24779 8.48978 10.2274 11.2096 17.2275 c 2.05353 5.28542 4.52401 13.2641 5.19155 27.8854 c 0.71982 15.8162 0.87269 20.5512 0.87269 60.5976 c 0 40.0486 -0.16464 44.7837 -0.87269 60.5976 c -0.66802 14.6237 -3.13802 22.5553 -5.19155 27.8407 c -2.71986 7.00014 -5.9607 12.0221 -11.2096 17.2722 c -5.24803 5.2478 -10.2269 8.48912 -17.2281 11.2106 c -5.28517 2.04643 -13.2636 4.48099 -27.8866 5.14667 c -15.8136 0.72913 -20.5455 0.87028 -60.5968 0.87028 c -40.0513 0 -44.7832 -0.23495 -60.5968 -0.87028 c -14.623 -0.65865 -22.5556 -3.09321 -27.8407 -5.14667 c -7.0011 -2.72148 -12.0259 -5.9628 -17.2739 -11.2106 c -5.24773 -5.25014 -8.48863 -10.2721 -11.2096 -17.2722 c -2.05352 -5.28541 -4.47792 -13.2171 -5.14546 -27.8407 c -0.71982 -15.8139 -0.87269 -20.5489 -0.87269 -60.5976 c 0 -40.0464 0.16465 -44.7813 0.87269 -60.5976 c 0.66803 -14.6213 3.09194 -22.6 5.14546 -27.8854 c 2.72101 -7.00014 5.96191 -11.9797 11.2096 -17.2275 c 5.24804 -5.2478 10.2728 -8.48912 17.2739 -11.2106 c 5.28517 -2.04643 13.2177 -4.52334 27.8407 -5.19137 c 15.816 -0.72913 20.5491 -0.87028 60.5968 -0.87028 Z m 80.0762 24.9005 c -9.93951 0 -18.0092 8.06807 -18.0092 18.0085 c 0 9.94042 8.06969 18.0085 18.0092 18.0085 c 9.94066 0 18.009 -8.06812 18.009 -18.0085 c 0 -9.94041 -8.0683 -18.0085 -18.009 -18.0085 Z m -80.0762 21.0405 c -42.5361 0 -76.9981 34.5092 -76.9981 77.0442 c 0 42.5373 34.4619 76.9971 76.9981 76.9971 c 42.5361 0 77.0439 -34.4598 77.0439 -76.9971 c 0 -42.5349 -34.5078 -77.0442 -77.0439 -77.0442 Z m 0 27.0598 c 27.6116 0 49.9844 22.3741 49.9844 49.9844 c 0 27.6126 -22.3728 49.9844 -49.9844 49.9844 c -27.6116 0 -49.9844 -22.3718 -49.9844 -49.9844 c 0 -27.6102 22.3728 -49.9844 49.9844 -49.9844 Z" />
            </g>
          </svg>
        </a>
      </div>

      <p className="absolute left-1/2 sm:transform -translate-x-1/2 text-xs sm:text-base">
        Contact us at{" "}
        <a href="mailto:evconceptillini@gmail.com">
          <u>evconceptillini@gmail.com</u>
        </a>{" "}
        for any inquiries.
      </p>
    </div>
  );
}
