import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Illini EV Concept",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <div
      className="sticky top-0 z-50 p-1.5 flex flex-row gap-4 text-white text-xl mb-2 items-center font-montserrat"
      style={{ backgroundColor: "#07407B" }}
    >
      <div>
        <Link href="/">
          <Image src="/images/evlogo.png" alt="evlogo" width="60" height="60" />
        </Link>
      </div>
      <div className="flex gap-10 ml-auto mr-10">
        <div>
          <Link href="/about">ABOUT</Link>
        </div>
        <div>
          <Link href="/team">OUR TEAM</Link>
        </div>
        <div>
          <Link href="/cars">OUR CARS</Link>
        </div>
        <div>
          <Link href="/sponsors">SPONSORS</Link>
        </div>
        <div>
          <Link href="/contacts">CONTACT US</Link>
        </div>
      </div>
    </div>
  );
}

function Footer() {
  return (
    <div className="bg-gray-100 flex flex-col flex-shrink-0 font-montserrat text-black text-center">
      <p>contact us at asdfas for any inquiries.</p>
    </div>
  );
}
