import Image from "next/image";

export const metadata = {
  title: "Our Team — Illini EV Concept",
  description: "Generated by create next app",
};

export default function Team() {
  // pres, treasurer, bizops x2, electrical x3, embedded x3 (VFDC, Neil Deo, Haoming), mech x2, autonomous ?,
  const items = [
    {
      id: 1,
      picture: "/images/team/ab.jpg",
      name: "Abigail Gillham",
      position: "President",
      info: "Computer Science 2027",
    },
    {
      id: 2,
      picture: "/images/team/jaimie.jpg",
      name: "Jaimie Li",
      position: "Treasurer",
      info: "Accountancy and Information Systems 2028",
    },
    {
      id: 3,
      picture: "/images/team/anthony.jpg",
      name: "Anthony Amella",
      position: "Electrical Co-Lead",
      info: "Electrical Engineering 2026",
    },
    {
      id: 4,
      picture: "/images/team/eric.jpg",
      name: "Eric Vo",
      position: "Electrical Co-Lead",
      info: "Electrical Engineering 2026",
    },
    {
      id: 5,
      picture: "/images/team/kathleen.jpg",
      name: "Kathleen Lum",
      position: "Electrical Co-Lead",
      info: "Electrical Engineering 2026",
    },
    {
      id: 6,
      picture: "/images/team/haoming.jpg",
      name: "Haoming Mei",
      position: "Embedded Co-Lead",
      info: "Computer Engineering 2026",
    },
    // {
    //   id: 7,
    //   picture: null,
    //   name: "Vervin Fernandez",
    //   info: "Computer Engineering 2026",
    // },
    {
      id: 7,
      picture: null,
      name: "Neil Deo",
      position: "Embedded Co-Lead",
      info: "Computer Engineering 2027",
    },
    {
      id: 8,
      picture: "/images/team/antheria.jpg",
      name: "Antheria Jiang",
      position: "Mechposites Co-Lead",
      info: "Mechanical Engineering 2026",
    },
    {
      id: 9,
      picture: "/images/team/nick_mech.jpg",
      name: "Nick Skweres",
      position: "Mechposites Co-Lead",
      info: "Mechanical Engineering 2026",
    },
    {
      id: 10,
      picture: "/images/team/sid.jpg",
      name: "Siddharth Gupta",
      position: "Autonomous Lead",
      info: "Physics + Computer Science 2025",
    },
    {
      id: 11,
      picture: "/images/team/kathy.jpg",
      name: "Kathryn Lee",
      position: "Business Operations Co-Lead",
      info: "Computer Science + Chemistry 2026",
    },
    {
      id: 12,
      picture: "/images/team/michael.jpg",
      name: "Michael Wang",
      position: "Business Operations Co-Lead",
      info: "Computer Science + Astronomy 2026",
    },
  ];

  const boxes = [
    {
      title: "Electrical",
      description:
        "Handles the end-to-end development and manufacturing of all electrical systems, including battery management, telemetry boards, and motor controllers.",
      image: "/images/team/electrical.png",
    },
    {
      title: "Embedded",
      description:
        "Customizes and programs microcontroller-based systems to manage and control the car’s electronic functions, coordinating with the vehicle’s overall system.",
      image: "/images/team/emb.png",
    },
    {
      title: "Mechposites",
      description:
        "Designs and manufactures the body, drivetrain, suspension, brakes, and steering components to ensure optimal safety, reliability, and performance.",
      image: "/images/team/mech.png",
    },
    {
      title: "Autonomous",
      description:
        "Integrates systems for autonomous vehicle capabilities, focusing on computer vision, advanced planning algorithms, and specialized hardware for smooth operation.",
      image: "/images/team/auto.png",
    },
    {
      title: "Business Operations",
      description:
        "Manages essential organizational needs such as internal consulting, inventory, purchases, sponsorships, accounting, and outreach, driving overall team efficiency and innovation.",
      image: "/images/team/bizops.png",
    },
  ];
  return (
    <div>
      <Image
        src="/images/contacts/classiccarcropped.jpg"
        alt="Classic Car"
        width={5000}
        height={500}
      />
      <h1
        className="font-semibold py-2 text-5xl px-4"
        style={{ backgroundColor: "#07407b", color: "#f7931e" }}
      >
        MEET THE TEAM
      </h1>
      <div className="text-2xl flex-col justify-center items-center">
        <p className="px-6 py-6">
          Our members come from various majors to build skills in engineering,
          design, and business. With over 80 members, the dedication and
          creativity of our team are crucial to our success. Members and alums
          have applied the skills they’ve gained to work at companies such as
          Apple, John Deere, McMaster, SpaceX, Texas Instruments, Tesla, and
          more.
        </p>

        <Image
          src="/images/ev_pose_all.JPG"
          alt="Comp Pic"
          width={2000}
          height={1000}
        />
      </div>
      <div>
        <h1 className="text-center font-semibold py-6 text-6xl px-4">
          2025-2026 EXEC
        </h1>
        {/* People */}
        <div className="p-6 in-h-screen">
          <div className="grid grid-cols-3 gap-6">
            {items.map((item) => (
              <div
                key={item.id}
                className="rounded-lg p-2 transition-shadow duration-300"
                // style={{ backgroundColor: '#07407b' }}
              >
                <div className="flex flex-col items-center text-center">
                  <img
                    src={item.picture}
                    alt={item.name}
                    className="w-64 h-64 rounded-full shadow-lg shadow-gray-400 mb-2 object-cover border-2 border-gray-100"
                  />
                  <h2 className="mt-2 font-bold">{item.position}</h2>
                  <h3
                    className="text-xl font-semibold mb-2"
                    style={{ color: "#f7931e" }}
                  >
                    {item.name}
                  </h3>
                  <p className="text-white text-sm leading-relaxed">
                    {item.info}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
        {/* <div className="flex flex-col items-center justify-center">
          <Image
            src="/images/walking_car_rain.JPG"
            alt="team pic"
            width={2000}
            height={1000}
          />
        </div> */}

        <div className="min-h-screen flex flex-col">
          <div className="flex items-center justify-center py-8">
            <div className="max-w-6xl w-full">
              <h1 className="font-semibold py-3 text-3xl">SUBTEAMS</h1>
              <p>
                At Illini EV Concept, our team is organized into specialized
                subteams, each responsible for different areas of our vehicle.
                We use industry-standard software such as SolidWorks and KiCAD
                to design, build, and operate every system of our cars. With a
                strong emphasis on mentoring, experienced members guide
                newcomers through hands-on projects, helping them develop
                practical skills and expertise. This structure allows members to
                focus on specific aspects of the vehicle, gaining in-depth
                knowledge and taking on increased responsibilities as they
                collaborate across subteams.
              </p>
            </div>
          </div>
          {boxes.map((box, index) => (
            <div
              key={index}
              className={`flex-1 flex items-center justify-center p-8`}
              style={{
                backgroundColor: index % 2 === 0 ? "#07407b" : "",
              }}
            >
              <div
                className={`max-w-6xl w-full flex items-center gap-8 ${
                  index % 2 === 1 ? "flex-row-reverse" : ""
                }`}
              >
                <div className="flex-1">
                  <h2
                    className="text-3xl font-bold mb-4"
                    style={{ color: "#f7931e" }}
                  >
                    {box.title}
                  </h2>
                  <p className="text-gray-200 text-lg leading-relaxed">
                    {box.description}
                  </p>
                </div>
                <div>
                  <img
                    src={box.image}
                    alt={box.title}
                    className="max-w-screen-sm object-cover shadow-md"
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// 'use client';

// import React from 'react';
// import './team.css'; // Import the CSS file

// export const metadata = {
//   title: "Contact Us — Illini EV Concept",
//   description: "Generated by create next app",
// };

// export default function Team() {
//   const items = [
//     {
//       id: 1,
//       picture: "/images/team/ab.jpg",
//       name: "Abigail Gillham",
//       position: "President",
//       info: "Computer Science 2027",
//     },
//     {
//       id: 2,
//       picture: "/images/team/jaimie.jpg",
//       name: "Jaimie Li",
//       position: "Treasurer",
//       info: "Accountancy and Information Systems 2028",
//     },
//     {
//       id: 3,
//       picture: "/images/team/anthony.jpg",
//       name: "Anthony Amella",
//       position: "Electrical Co-Lead",
//       info: "Electrical Engineering 2026",
//     },
//     {
//       id: 4,
//       picture: "/images/team/eric.jpg",
//       name: "Eric Vo",
//       position: "Electrical Co-Lead",
//       info: "Electrical Engineering 2026",
//     },
//     {
//       id: 5,
//       picture: "/images/team/kathleen.jpg",
//       name: "Kathleen Lum",
//       position: "Electrical Co-Lead",
//       info: "Electrical Engineering 2026",
//     },
//     {
//       id: 6,
//       picture: "/images/team/haoming.jpg",
//       name: "Haoming Mei",
//       position: "Embedded Co-Lead",
//       info: "Computer Engineering 2026",
//     },
//     {
//       id: 7,
//       picture: "/images/team/neil.png",
//       name: "Neil Deo",
//       position: "Embedded Co-Lead",
//       info: "Computer Engineering 2027",
//     },
//     {
//       id: 8,
//       picture: "/images/team/antheria.jpg",
//       name: "Antheria Jiang",
//       position: "Mechposites Co-Lead",
//       info: "Mechanical Engineering 2026",
//     },
//     {
//       id: 9,
//       picture: "/images/team/nick_mech.jpg",
//       name: "Nick Skweres",
//       position: "Mechposites Co-Lead",
//       info: "Mechanical Engineering 2026",
//     },
//     {
//       id: 10,
//       picture: "/images/team/sid.jpg",
//       name: "Siddharth Gupta",
//       position: "Autonomous Lead",
//       info: "Physics + Computer Science 2025",
//     },
//     {
//       id: 11,
//       picture: "/images/team/kathy.jpg",
//       name: "Kathryn Lee",
//       position: "Business Operations Co-Lead",
//       info: "Computer Science + Chemistry 2026",
//     },
//     {
//       id: 12,
//       picture: "/images/team/michael.jpg",
//       name: "Michael Wang",
//       position: "Business Operations Co-Lead",
//       info: "Computer Science + Astronomy 2026",
//     },
//   ];

//   const boxes = [
//     {
//       title: "Electrical",
//       description:
//         "Handles the end-to-end development and manufacturing of all electrical systems, including battery management, telemetry boards, and motor controllers.",
//       image: "/images/team/electrical.png",
//       color: "#4a90e2"
//     },
//     {
//       title: "Embedded",
//       description:
//         "Customizes and programs microcontroller-based systems to manage and control the car's electronic functions, coordinating with the vehicle's overall system.",
//       image: "/images/team/emb.png",
//       color: "#f7931e"
//     },
//     {
//       title: "Mechposites",
//       description:
//         "Designs and manufactures the body, drivetrain, suspension, brakes, and steering components to ensure optimal safety, reliability, and performance.",
//       image: "/images/team/mech.png",
//       color: "#2ecc71"
//     },
//     {
//       title: "Autonomous",
//       description:
//         "Integrates systems for autonomous vehicle capabilities, focusing on computer vision, advanced planning algorithms, and specialized hardware for smooth operation.",
//       image: "/images/team/auto.png",
//       color: "#e74c3c"
//     },
//     {
//       title: "Business Operations",
//       description:
//         "Manages essential organizational needs such as internal consulting, inventory, purchases, sponsorships, accounting, and outreach, driving overall team efficiency and innovation.",
//       image: "/images/team/bizops.png",
//       color: "#9b59b6"
//     },
//   ];

//   return (
//     <div className='pb-8'>
//       {/* Hero Section */}
//       <div className="relative">
//         <div className="absolute inset-0 circuit-bg"></div>
//         <img
//           src="/images/contacts/classiccarcropped.jpg"
//           alt="Classic Car"
//           className="w-full h-64 md:h-96 object-cover opacity-80"
//         />
//         <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-transparent to-black/70"></div>
//       </div>
      
//       <div className="relative -mt-20">
//         <h1 className="hero-title electric-title font-black text-center">
//           MEET THE TEAM
//         </h1>
//       </div>

//       {/* Introduction Section */}
//       <div className="max-w-6xl mx-auto px-6 py-12">
//         <div className="neon-card rounded-2xl p-8 mb-12">
//           <p className="intro-text text-gray-300 text-center leading-relaxed">
//             Our members come from various majors to build skills in engineering,
//             design, and business. With over <span className="text-blue-400 font-semibold">80 members</span>, the dedication and
//             creativity of our team are crucial to our success. Members and alums
//             have applied the skills they've gained to work at companies such as
//             <span className="text-orange-400 font-semibold"> Apple, John Deere, McMaster, SpaceX, Texas Instruments, Tesla</span>, and
//             more.
//           </p>
//         </div>

//         <div className="rounded-2xl overflow-hidden shadow-2xl mb-16">
//           <img
//             src="/images/ev_pose_all.JPG"
//             alt="Team Photo"
//             className="w-full h-auto"
//           />
//         </div>
//       </div>

//       {/* Executive Team */}
//       <div className="max-w-7xl mx-auto px-4">
//         <h2 className="exec-title electric-title font-black text-center mb-16">
//           2025-2026 EXEC
//         </h2>
        
//         <div className="team-grid mb-20">
//           {items.map((item, index) => (
//             <div
//               key={item.id}
//               className="neon-card rounded-2xl p-6"
//               style={{
//                 animationDelay: `${index * 0.1}s`,
//                 animation: 'slide-in 0.6s ease forwards'
//               }}
//             >
//               <div className="flex flex-col items-center text-center">
//                 <div className="relative mb-6">
//                   <img
//                     src={item.picture || "/images/team/placeholder.jpg"}
//                     alt={item.name}
//                     className="team-image team-image-size rounded-full object-cover border-2 border-blue-400/40 shadow-lg"
//                   />
//                   <div className="absolute inset-0 rounded-full bg-gradient-to-tr from-blue-400/15 to-transparent"></div>
//                 </div>
                
//                 <div className="space-y-2">
//                   <h3 className="text-blue-400 font-semibold text-sm uppercase tracking-wider">
//                     {item.position}
//                   </h3>
//                   <h4 className="text-xl font-bold text-white mb-2">
//                     {item.name}
//                   </h4>
//                   <p className="text-gray-400 text-sm">
//                     {item.info}
//                   </p>
//                 </div>
//               </div>
//             </div>
//           ))}
//         </div>

//         {/* Subteams Section */}
//         <div>
//           <h2 className="text-4xl md:text-5xl font-bold text-center mb-8">
//             <span className="electric-title">SUBTEAMS</span>
//           </h2>
          
//           <div className="max-w-4xl mx-auto mb-12">
//             <div className="neon-card rounded-2xl p-8">
//               <p className="text-gray-300 text-center leading-relaxed">
//                 At Illini EV Concept, our team is organized into specialized
//                 subteams, each responsible for different areas of our vehicle.
//                 We use industry-standard software such as <span className="text-blue-400">SolidWorks</span> and <span className="text-blue-400">KiCAD</span>
//                 to design, build, and operate every system of our cars. With a
//                 strong emphasis on mentoring, experienced members guide
//                 newcomers through hands-on projects, helping them develop
//                 practical skills and expertise.
//               </p>
//             </div>
//           </div>

//           <div className="space-y-8">
//             {boxes.map((box, index) => (
//               <div
//                 key={index}
//                 className="subteam-card rounded-2xl p-8 mx-4"
//                 style={{ borderLeftColor: box.color }}
//               >
//                 <div className={`flex flex-col lg:flex-row items-center gap-8 ${
//                   index % 2 === 1 ? 'lg:flex-row-reverse' : ''
//                 } subteam-section`}>
//                   <div className="flex-1 space-y-4">
//                     <h3
//                       className="text-3xl md:text-4xl font-bold"
//                       style={{ color: box.color }}
//                     >
//                       {box.title}
//                     </h3>
//                     <p className="text-gray-300 leading-relaxed text-lg">
//                       {box.description}
//                     </p>
//                   </div>
//                   <div className="flex-shrink-0">
//                     <img
//                       src={box.image}
//                       alt={box.title}
//                       className="subteam-image w-80 h-60 object-cover rounded-xl shadow-2xl"
//                       style={{
//                         filter: `drop-shadow(0 10px 20px ${box.color}40)`
//                       }}
//                     />
//                   </div>
//                 </div>
//               </div>
//             ))}
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// }