import Image from "next/image";

export const metadata = {
  title: "Our Team — Illini EV Concept",
  description: "Generated by create next app",
};

export default function Team() {
  // pres, treasurer, bizops x2, electrical x3, embedded x3 (VFDC, Neil Deo, Haoming), mech x2, autonomous ?,
  const items = [
    {
      id: 1,
      picture: "/images/team/ab.jpg",
      name: "Abigail Gillham",
      position: "President",
      info: "Computer Science 2027",
    },
    {
      id: 2,
      picture: "/images/team/jaimie.jpg",
      name: "Jaimie Li",
      position: "Treasurer",
      info: "Accountancy and Information Systems 2028",
    },
    {
      id: 3,
      picture: "/images/team/anthony.jpg",
      name: "Anthony Amella",
      position: "Electrical Co-Lead",
      info: "Electrical Engineering 2026",
    },
    {
      id: 4,
      picture: "/images/team/eric.jpg",
      name: "Eric Vo",
      position: "Electrical Co-Lead",
      info: "Electrical Engineering 2026",
    },
    {
      id: 5,
      picture: "/images/team/kathleen.jpg",
      name: "Kathleen Lum",
      position: "Electrical Co-Lead",
      info: "Electrical Engineering 2026",
    },
    {
      id: 6,
      picture: "/images/team/haoming.jpg",
      name: "Haoming Mei",
      position: "Embedded Co-Lead",
      info: "Computer Engineering 2026",
    },
    // {
    //   id: 7,
    //   picture: null,
    //   name: "Vervin Fernandez",
    //   info: "Computer Engineering 2026",
    // },
    {
      id: 7,
      picture: null,
      name: "Neil Deo",
      position: "Embedded Co-Lead",
      info: "Computer Engineering 2027",
    },
    {
      id: 8,
      picture: "/images/team/antheria.jpg",
      name: "Antheria Jiang",
      position: "Mechposites Co-Lead",
      info: "Mechanical Engineering 2026",
    },
    {
      id: 9,
      picture: "/images/team/nick_mech.jpg",
      name: "Nick Skweres",
      position: "Mechposites Co-Lead",
      info: "Mechanical Engineering 2026",
    },
    {
      id: 10,
      picture: "/images/team/sid.jpg",
      name: "Siddharth Gupta",
      position: "Autonomous Lead",
      info: "Physics + Computer Science 2025",
    },
    {
      id: 11,
      picture: "/images/team/kathy.jpg",
      name: "Kathryn Lee",
      position: "Business Operations Co-Lead",
      info: "Computer Science + Chemistry 2026",
    },
    {
      id: 12,
      picture: "/images/team/michael.jpg",
      name: "Michael Wang",
      position: "Business Operations Co-Lead",
      info: "Computer Science + Astronomy 2026",
    },
  ];

  const boxes = [
    {
      title: "Electrical",
      description:
        "Handles the end-to-end development and manufacturing of all electrical systems, including battery management, telemetry boards, and motor controllers.",
      image: "/images/team/electrical.png",
    },
    {
      title: "Embedded",
      description:
        "Customizes and programs microcontroller-based systems to manage and control the car’s electronic functions, coordinating with the vehicle’s overall system.",
      image: "/images/team/emb.png",
    },
    {
      title: "Mechposites",
      description:
        "Designs and manufactures the body, drivetrain, suspension, brakes, and steering components to ensure optimal safety, reliability, and performance.",
      image: "/images/team/mech.png",
    },
    {
      title: "Autonomous",
      description:
        "Integrates systems for autonomous vehicle capabilities, focusing on computer vision, advanced planning algorithms, and specialized hardware for smooth operation.",
      image: "/images/team/auto.png",
    },
    {
      title: "Business Operations",
      description:
        "Manages essential organizational needs such as internal consulting, inventory, purchases, sponsorships, accounting, and outreach, driving overall team efficiency and innovation.",
      image: "/images/team/bizops.png",
    },
  ];
  return (
    <div>
      <div className="gradient-overlay">
        <Image
          src="/images/contacts/classiccarcropped.jpg"
          alt="Classic Car"
          width={5000}
          height={500}
        />
      </div>
      <div className="section-header">
      <h1
        className="section-title"
      >
        MEET THE TEAM
      </h1>
      </div>
      <div className="text-2xl flex-col justify-center items-center">
        <p className="px-6 py-6">
          Our members come from various majors to build skills in engineering,
          design, and business. With over 80 members, the dedication and
          creativity of our team are crucial to our success. Members and alums
          have applied the skills they’ve gained to work at companies such as
          Apple, John Deere, McMaster, SpaceX, Texas Instruments, Tesla, and
          more.
        </p>

        <Image
          src="/images/ev_pose_all.JPG"
          alt="Comp Pic"
          width={2000}
          height={1000}
        />
      </div>
      <div>
        <h1 className="text-center font-semibold py-6 text-6xl px-4">
          2025-2026 EXEC
        </h1>
        {/* People */}
        <div className="p-6 in-h-screen">
          <div className="grid grid-cols-3 gap-6">
            {items.map((item) => (
              <div
                key={item.id}
                className="rounded-lg p-2 transition-shadow duration-300"
                // style={{ backgroundColor: '#07407b' }}
              >
                <div className="flex flex-col items-center text-center">
                  <img
                    src={item.picture}
                    alt={item.name}
                    className="w-64 h-64 rounded-full shadow-lg shadow-gray-400 mb-2 object-cover border-2 border-gray-100"
                  />
                  <h2 className="mt-2 font-bold">{item.position}</h2>
                  <h3
                    className="text-xl font-semibold mb-2"
                    style={{ color: "#f7931e" }}
                  >
                    {item.name}
                  </h3>
                  <p className="text-white text-sm leading-relaxed">
                    {item.info}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
        {/* <div className="flex flex-col items-center justify-center">
          <Image
            src="/images/walking_car_rain.JPG"
            alt="team pic"
            width={2000}
            height={1000}
          />
        </div> */}

        <div className="min-h-screen flex flex-col">
          <div className="flex items-center justify-center py-8">
            <div className="max-w-6xl w-full">
              <h1 className="font-semibold py-3 text-3xl">SUBTEAMS</h1>
              <p>
                At Illini EV Concept, our team is organized into specialized
                subteams, each responsible for different areas of our vehicle.
                We use industry-standard software such as SolidWorks and KiCAD
                to design, build, and operate every system of our cars. With a
                strong emphasis on mentoring, experienced members guide
                newcomers through hands-on projects, helping them develop
                practical skills and expertise. This structure allows members to
                focus on specific aspects of the vehicle, gaining in-depth
                knowledge and taking on increased responsibilities as they
                collaborate across subteams.
              </p>
            </div>
          </div>
          {boxes.map((box, index) => (
            <div
              key={index}
              className={`flex-1 flex items-center justify-center p-8`}
              style={{
                backgroundColor: index % 2 === 0 ? "#07407b" : "",
              }}
            >
              <div
                className={`max-w-6xl w-full flex items-center gap-8 ${
                  index % 2 === 1 ? "flex-row-reverse" : ""
                }`}
              >
                <div className="flex-1">
                  <h2
                    className="text-3xl font-bold mb-4"
                    style={{ color: "#f7931e" }}
                  >
                    {box.title}
                  </h2>
                  <p className="text-gray-200 text-lg leading-relaxed">
                    {box.description}
                  </p>
                </div>
                <div>
                  <img
                    src={box.image}
                    alt={box.title}
                    className="max-w-screen-sm object-cover shadow-md"
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}