import Image from "next/image";

export const metadata = {
  title: "Our Team — Illini EV Concept",
  description: "Generated by create next app",
};

export default function Team() {
  const items = [
    {
      id: 1,
      picture: "/images/team/ab.jpg",
      name: "Abigail Gillham",
      position: "President",
      info: "Computer Science 2027",
    },
    {
      id: 2,
      picture: "/images/team/jaimie.jpg",
      name: "Jaimie Li",
      position: "Treasurer",
      info: "Accountancy and Information Systems 2028",
    },
    {
      id: 3,
      picture: "/images/team/ethan_rybka.jpg",
      name: "Ethan Rybka",
      position: "ELectrical Co-Lead",
      info: "Electrical Engineering 2028"
    },
    // {
    //   id: 3,
    //   picture: "/images/team/anthony.jpg",
    //   name: "Anthony Amella",
    //   position: "Electrical Co-Lead",
    //   info: "Electrical Engineering 2026",
    // },
    // {
    //   id: 4,
    //   picture: "/images/team/eric.jpg",
    //   name: "Eric Vo",
    //   position: "Electrical Co-Lead",
    //   info: "Electrical Engineering 2026",
    // },
    // {
    //   id: 4,
    //   picture: "/images/team/eric.jpg",
    //   name: "Eric Vo",
    //   position: "Electrical Co-Lead",
    //   info: "Electrical Engineering 2026",
    // },
    // {
    //   id: 5,
    //   picture: "/images/team/kathleen.jpg",
    //   name: "Kathleen Lum",
    //   position: "Electrical Co-Lead",
    //   info: "Electrical Engineering 2026",
    // },
    // {
    //   id: 6,
    //   picture: "/images/team/haoming.jpg",
    //   name: "Haoming Mei",
    //   position: "Embedded Co-Lead",
    //   info: "Computer Engineering 2026",
    // },
    // {
    //   id: 7,
    //   picture: null,
    //   name: "Neil Deo",
    //   position: "Embedded Co-Lead",
    //   info: "Computer Engineering 2027",
    // },
    {
      id: 4,
      picture: "/images/team/mithra_thratta.png",
      name: "Mithra Thratta",
      position: "Embedded Co-Lead",
      info: "Computer Engineering 2028"
    },
    {
      id: 5,
      picture: "/images/team/carlos_arriola.jpg",
      name: "Carlos Arriola",
      position: "Embedded Co-Lead",
      info: "Computer Engineering 2028"
    },
    // {
    //   id: 8,
    //   picture: "/images/team/antheria.jpg",
    //   name: "Antheria Jiang",
    //   position: "Mechposites Co-Lead",
    //   info: "Mechanical Engineering 2026",
    // },
    // {
    //   id: 9,
    //   picture: "/images/team/nick_mech.jpg",
    //   name: "Nick Skweres",
    //   position: "Mechposites Co-Lead",
    //   info: "Mechanical Engineering 2026",
    // },
    {
      id: 6,
      picture: "/images/team/alex_james.jpg",
      name: "Alex James",
      position: "Mechposites Co-Lead",
      info: "Mechanical Engineering 2027",
    },
    {
      id: 7,
      picture: "/images/team/nicholas_wszolek.jpg",
      name: "Nick Wszolek",
      position: "Mechposites Co-Lead",
      info: "Mechanical Engineering 2027",
    },
    // {
    //   id: 10,
    //   picture: "/images/team/sid.jpg",
    //   name: "Siddharth Gupta",
    //   position: "Autonomous Lead",
    //   info: "Physics + Computer Science 2025",
    // },
    {
      id: 8,
      picture: "/images/team/shayan_rahman.jpg",
      name: "Shayan Rahman",
      position: "Autonomous Co-Lead",
      info: "Computer Engineering 2028",
    },
    {
      id: 9,
      picture: "/images/team/anay_joshi.jpeg",
      name: "Anay Joshi",
      position: "Autonomous Co-Lead",
      info: "CS + Physics 2028",
    },
    // {
    //   id: 10,
    //   picture: "/images/team/kathy.jpg",
    //   name: "Kathryn Lee",
    //   position: "Business Operations Co-Lead",
    //   info: "Computer Science + Chemistry 2026",
    // },
    {
      id: 10,
      picture: "/images/team/michael.jpg",
      name: "Michael Wang",
      position: "Business Operations Lead",
      info: "Computer Science + Astronomy 2026",
    },
  ];

  const boxes = [
    {
      title: "Electrical",
      description:
        "Handles the end-to-end development and manufacturing of all electrical systems, including battery management, telemetry boards, and motor controllers.",
      image: "/images/team/electrical.webp",
      width: 900,
      height: 475,
    },
    {
      title: "Embedded",
      description:
        "Customizes and programs microcontroller-based systems to manage and control the car’s electronic functions, coordinating with the vehicle’s overall system.",
      image: "/images/team/emb.webp",
      width: 900,
      height: 468,
    },
    {
      title: "Mechposites",
      description:
        "Designs and manufactures the body, drivetrain, suspension, brakes, and steering components to ensure optimal safety, reliability, and performance.",
      image: "/images/team/mech.webp",
      width: 900,
      height: 447,
    },
    {
      title: "Autonomous",
      description:
        "Integrates systems for autonomous vehicle capabilities, focusing on computer vision, advanced planning algorithms, and specialized hardware for smooth operation.",
      image: "/images/team/auto.webp",
      width: 900,
      height: 454,
    },
    {
      title: "Business Operations",
      description:
        "Manages essential organizational needs such as internal consulting, inventory, purchases, sponsorships, accounting, and outreach, driving overall team efficiency and innovation.",
      image: "/images/team/bizops.webp",
      width: 900,
      height: 544,
    },
  ];
  return (
    <div>
      <div className="gradient-overlay">
        <Image
          src="/images/contacts/classiccarcropped.jpg"
          alt="Classic Car"
          width={2560}
          height={480}
          priority
          sizes="100vw"
        />
      </div>
      <div className="section-header">
      <h1
        className="section-title"
      >
        MEET THE TEAM
      </h1>
      </div>
      <div className="text-2xl flex-col justify-center items-center mx-4 sm:mx-8 md:mx-12 lg:mx-20">
        <p className="flex text-center lg:flex-row lg:py-6 lg:px-4 space-y-8 md:space-y-0 md:space-x-12 text-sm lg:text-2xl lg:mb-10 lg:mt-10 my-5">
          Our members come from various majors to build skills in engineering,
          design, and business. With over 80 members, the dedication and
          creativity of our team are crucial to our success. Members and alums
          have applied the skills they've gained to work at companies such as
          Apple, John Deere, McMaster, SpaceX, Texas Instruments, Tesla, and
          more.
        </p>

        <Image
          src="/images/ev_pose_all.JPG"
          alt="Comp Pic"
          width={2048}
          height={955}
          priority
          sizes="100vw"
          className="w-full h-auto"
        />
      </div>
      <div>
        <h1 className="text-center font-semibold py-6 text-3xl sm:text-4xl md:text-5xl lg:text-6xl px-4">
          2026-2027 EXEC
        </h1>
        {/* People */}
        <div className="p-3 sm:p-4 md:p-6 in-h-screen">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
            {items.map((item) => (
              <div
                key={item.id}
                className="rounded-lg p-2 transition-shadow duration-300"
                // style={{ backgroundColor: '#07407b' }}
              >
                <div className="flex flex-col items-center text-center">
                  <Image
                    src={item.picture}
                    alt={item.name}
                    width={256}
                    height={256}
                    sizes="256px"
                    className="w-48 h-48 sm:w-56 sm:h-56 md:w-64 md:h-64 rounded-full shadow-lg shadow-gray-400 mb-2 object-cover border-2 border-gray-100"
                  />
                  <h2 className="mt-2 font-bold text-sm sm:text-base">{item.position}</h2>
                  <h3
                    className="text-lg sm:text-xl font-semibold mb-2"
                    style={{ color: "#f7931e" }}
                  >
                    {item.name}
                  </h3>
                  <p className="text-white text-xs sm:text-sm leading-relaxed">
                    {item.info}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
        {/* <div className="flex flex-col items-center justify-center">
          <Image
            src="/images/walking_car_rain.JPG"
            alt="team pic"
            width={2000}
            height={1000}
          />
        </div> */}

        <div className="min-h-screen flex flex-col">
          <div className="flex items-center justify-center py-8 px-4 sm:px-6 md:px-8">
            <div className="max-w-6xl w-full">
              <h1 className="font-semibold py-3 text-2xl sm:text-3xl">SUBTEAMS</h1>
              <p className="text-sm sm:text-base">
                At Illini EV Concept, our team is organized into specialized
                subteams, each responsible for different areas of our vehicle.
                We use industry-standard software such as SolidWorks and KiCAD
                to design, build, and operate every system of our cars. With a
                strong emphasis on mentoring, experienced members guide
                newcomers through hands-on projects, helping them develop
                practical skills and expertise. This structure allows members to
                focus on specific aspects of the vehicle, gaining in-depth
                knowledge and taking on increased responsibilities as they
                collaborate across subteams.
              </p>
            </div>
          </div>
          {boxes.map((box, index) => (
            <div
              key={index}
              className={`flex-1 flex items-center justify-center p-4 sm:p-6 md:p-8`}
              style={{
                backgroundColor: index % 2 === 0 ? "#07407b" : "",
              }}
            >
              <div
                className={`max-w-6xl w-full flex flex-col md:flex-row items-center gap-4 sm:gap-6 md:gap-8 ${
                  index % 2 === 1 ? "md:flex-row-reverse" : ""
                }`}
              >
                <div className="flex-1">
                  <h2
                    className="text-2xl sm:text-3xl font-bold mb-3 sm:mb-4"
                    style={{ color: "#f7931e" }}
                  >
                    {box.title}
                  </h2>
                  <p className="text-gray-200 text-sm sm:text-base md:text-lg leading-relaxed">
                    {box.description}
                  </p>
                </div>
                <div className="w-full md:w-[24rem] lg:w-[28rem] md:shrink-0">
                  <Image
                    src={box.image}
                    alt={box.title}
                    width={box.width}
                    height={box.height}
                    sizes="(min-width: 1024px) 448px, (min-width: 768px) 384px, 100vw"
                    className="w-full h-auto shadow-md"
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}