import './sponsors.css';
import Image from "next/image";
import Link from 'next/link';

export const metadata = {
  title: "Our Sponsors — Illini EV Concept",
  description: "Generated by create next app",
};

export default function Sponsors() {
    return (
        <div>
            <div className='gradient-overlay'>
                <Image
                    src="/images/contacts/classiccarcropped.jpg"
                    alt="Classic Car"
                    width={5000}
                    height={500}
                />
            </div>
            <div className="section-header">
                <h2 className="section-title">SPONSORS</h2>
            </div>

            <div className="sponsor">
                <Image
                    src="/images/sponsors/altium.jpg"
                    alt="altium sponsor"
                    width={500}
                    height={300}
                />
                <Image
                    src="/images/sponsors/altair.jpg"
                    alt="altair sponsor"
                    width={500}
                    height={300}
                />
            </div>

            <div className="my-20 mx-20 text-center text-sm lg:text-2xl">
                <p>
                    A huge thank you to all our sponsors! Your support has been essential in helping us achieve our
                    goals and in fostering the education and experience of our members and community.
                </p>
                <p className="mt-5">
                    If you’re not yet a sponsor but are interested, we appreciate your consideration!
                    Please review our sponsorship brochure and <Link href="/contacts" className="text-orange-300 underline">contact us</Link>.
                </p>
            </div>

            <div className="pdf-container flex justify-center mt-8">
                <iframe
                    src="https://evconcept.engr.illinois.edu/files/2024/09/Sponsorship_Brochure_2024-2025.pdf"
                    width="70%"
                    height="800px"
                    style={{ border: "none" }}
                    title="Sponsorship Brochure"
                />
            </div>
        </div>
    );
}
