import "./sponsors.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Our Sponsors — Illini EV Concept",
  description: "Generated by create next app",
};

const sponsors = [
  {
    src: "/images/sponsors/logo-700x400-Altium.png",
    alt: "Altium",
    href: "https://www.altium.com/",
  },
  {
    src: "/images/sponsors/Milwaukee-Logo.png",
    alt: "Milwaukee Tool",
    href: "https://www.milwaukeetool.com/",
  },
  {
    src: "/images/sponsors/siemens-logo.png",
    alt: "Siemens",
    href: "https://www.siemens.com/",
  },
];

export default function Sponsors() {
  return (
    <div>
      <div className="gradient-overlay">
        <Image
          src="/images/contacts/classiccarcropped.jpg"
          alt="Classic Car"
          width={2560}
          height={480}
          priority
          sizes="100vw"
        />
      </div>
      <div className="section-header">
        <h2 className="section-title">SPONSORS</h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8 mx-4 sm:mx-8 md:mx-12 lg:mx-20 mt-12 mb-8">
        {sponsors.map((sponsor) => (
          <a
            key={sponsor.src}
            href={sponsor.href}
            target="_blank"
            rel="noopener noreferrer"
            className="relative block w-full max-w-sm mx-auto md:max-w-none aspect-[5/3] bg-[#202020] hover:bg-[#2A2A2A] transition-colors rounded"
          >
            <Image
              src={sponsor.src}
              alt={sponsor.alt}
              fill
              sizes="(min-width: 768px) 30vw, 90vw"
              className="object-contain p-3 md:p-4"
            />
          </a>
        ))}
      </div>

      <div className="my-10 mx-5 md:my-20 md:mx-20 text-center text-sm lg:text-2xl">
        <p>
          A huge thank you to all our sponsors! Your support has been essential
          in helping us achieve our goals and in fostering the education and
          experience of our members and community.
        </p>
        <p className="mt-5">
          If you&apos;re not yet a sponsor but are interested, we appreciate your
          consideration! Please review our sponsorship brochure and{" "}
          <Link href="/contacts" className="text-orange-300 underline">
            contact us
          </Link>
          .
        </p>
      </div>

      <div className="flex justify-center mt-8 px-2 md:px-0">
        <iframe
          src="/Sponsorship_Proposal.pdf"
          className="w-full md:w-[95%] lg:w-[70%] h-[500px] md:h-[600px] lg:h-[800px] border-none"
          title="Sponsorship Brochure"
        />
      </div>
    </div>
  );
}
